<?

// Original module written by Marco Scutari.
// Rewritten and considerably shortened and made more Drupal-friendly
// by Earl Miles.

function paging_help($section) {
  switch ($section) {
    case 'admin/help#paging':
      return t("<p>Break long pages into smaller ones by means of " .
               "a \"page\" tag:</p>\n" .
               "<pre>\n" .
               "first page here.\n" .
               "&lt;!-- page --&gt;\n" .
               "second page here.\n" .
               "&lt;!-- page --&gt;\n" .
               "more pages here.\n");
    case 'admin/modules#description':
      return t("Allow users to use a tag to break a node up into multiple pages.");
  }
}

function paging_nodeapi(&$node, $op, $teaser = NULL, $page = NULL) {
  switch ($op) {

    case 'load':
      // Set up our pages on load.
      if (ereg("<!-- page -->", $node->body)) {
        $node->pages = explode("<!-- page -->", $node->body);
      }

    case 'form pre':
    case 'fields':
      // Replace the "pg" tag with the original "page" when the page
      // is about to be saved or the edit form is displayed.
      $node-> body = str_replace("<!-- pg -->", "<!-- page -->", $node->body);
      break;

    case 'validate':
       //  Replace the "page" tag not to break page preview.
      $node-> body = str_replace("<!-- page -->", "<!-- pg -->", $node->body);
      break;

    case 'view':
      // check paging is really needed and avoid paging 
      // printer friendly pages as well.
      if (!$teaser && !empty($node->pages) && arg(3) != 'print') {
        // This is a cheat to load the pager variables.
        pager_query("SELECT 1", 1, 0, "SELECT " . count($node->pages));
        global $pager_page_array;
        $page = isset($pager_page_array[0]) ? $pager_page_array[0] : 0;

        $node->body = check_markup($node->pages[$page], $node->filter, false);
        $node->body .= theme('pager', NULL, 0);
      }
      else if ($teaser && !empty($node->pages)) {
        // check to see if the teaser is longer than our first page.
        if (strlen($node->teaser) > strlen($node->pages[0])) {
          $node->teaser = check_markup($node->pages[0], $node->filter, false);
          $node->readmore = true;
        }
      }
  }
}

?>

