<?php
/**
 * @file
 * Install hooks for the Paging module.
 */

/**
 * Implementation of hook_uninstall().
 */
function paging_uninstall() {
  // Delete all variables starting with "paging" in their name.
  db_query("DELETE FROM {variable} WHERE name LIKE 'paging%'");
  db_query("DELETE FROM {filter} WHERE module = 'paging'");
}

/**
 * Remove 5 -> 6 Upgrade function.
 */
function paging_update_last_removed() {
  return 6000;
}

/**
 * Drupal 6 -> Drupal 7 upgrade path.
 */
// @todo
